name: 'DrupalQA'
description: 'Runs QA tools for a Drupal website'
inputs:
  php-version:  # id of input
    description: 'PHP version.'
    required: false
    default: '7.4'
  web-root:
    description: 'Web root (document root). This is set to web by default. Do not include trailing slash.'
    required: false
    default: 'web'
  checks:
    description: 'Checks to run. This is a YAML formatted structure and must begin with a pipe character.'
    required: false
    default: ''
outputs: {}
runs:
  using: 'node12'
  main: 'dist/index.js'
